<?php
/**
 * TemplatestemplateIdaddFieldsFieldsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocSpring;

/**
 * TemplatestemplateIdaddFieldsFieldsTest Class Doc Comment
 *
 * @category    Class
 * @description TemplatestemplateIdaddFieldsFields
 * @package     DocSpring
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TemplatestemplateIdaddFieldsFieldsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TemplatestemplateIdaddFieldsFields"
     */
    public function testTemplatestemplateIdaddFieldsFields()
    {
    }

    /**
     * Test attribute "background_color_field_name"
     */
    public function testPropertyBackgroundColorFieldName()
    {
    }

    /**
     * Test attribute "uppercase"
     */
    public function testPropertyUppercase()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "barcode_symbology"
     */
    public function testPropertyBarcodeSymbology()
    {
    }

    /**
     * Test attribute "min_length"
     */
    public function testPropertyMinLength()
    {
    }

    /**
     * Test attribute "integer"
     */
    public function testPropertyInteger()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "comb_value_offset"
     */
    public function testPropertyCombValueOffset()
    {
    }

    /**
     * Test attribute "image_gravity"
     */
    public function testPropertyImageGravity()
    {
    }

    /**
     * Test attribute "overflow"
     */
    public function testPropertyOverflow()
    {
    }

    /**
     * Test attribute "qrcode_color"
     */
    public function testPropertyQrcodeColor()
    {
    }

    /**
     * Test attribute "color_field_required"
     */
    public function testPropertyColorFieldRequired()
    {
    }

    /**
     * Test attribute "background_color_field_required"
     */
    public function testPropertyBackgroundColorFieldRequired()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image_scale_type"
     */
    public function testPropertyImageScaleType()
    {
    }

    /**
     * Test attribute "exclusive_minimum"
     */
    public function testPropertyExclusiveMinimum()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "number_condition_range_exclusive_max"
     */
    public function testPropertyNumberConditionRangeExclusiveMax()
    {
    }

    /**
     * Test attribute "invert_boolean_condition"
     */
    public function testPropertyInvertBooleanCondition()
    {
    }

    /**
     * Test attribute "shape_fill_color_field_name"
     */
    public function testPropertyShapeFillColorFieldName()
    {
    }

    /**
     * Test attribute "static"
     */
    public function testPropertyStatic()
    {
    }

    /**
     * Test attribute "shape_border_color_field_name"
     */
    public function testPropertyShapeBorderColorFieldName()
    {
    }

    /**
     * Test attribute "v_alignment"
     */
    public function testPropertyVAlignment()
    {
    }

    /**
     * Test attribute "bold"
     */
    public function testPropertyBold()
    {
    }

    /**
     * Test attribute "shape_border_width"
     */
    public function testPropertyShapeBorderWidth()
    {
    }

    /**
     * Test attribute "comb_number_of_cells"
     */
    public function testPropertyCombNumberOfCells()
    {
    }

    /**
     * Test attribute "shape_border_color"
     */
    public function testPropertyShapeBorderColor()
    {
    }

    /**
     * Test attribute "comb"
     */
    public function testPropertyComb()
    {
    }

    /**
     * Test attribute "typeface"
     */
    public function testPropertyTypeface()
    {
    }

    /**
     * Test attribute "shape_type"
     */
    public function testPropertyShapeType()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "display_type"
     */
    public function testPropertyDisplayType()
    {
    }

    /**
     * Test attribute "check_color"
     */
    public function testPropertyCheckColor()
    {
    }

    /**
     * Test attribute "multiline_lines"
     */
    public function testPropertyMultilineLines()
    {
    }

    /**
     * Test attribute "multiline"
     */
    public function testPropertyMultiline()
    {
    }

    /**
     * Test attribute "true_text"
     */
    public function testPropertyTrueText()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "font_size"
     */
    public function testPropertyFontSize()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "alignment"
     */
    public function testPropertyAlignment()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "auto_calculate_max_length"
     */
    public function testPropertyAutoCalculateMaxLength()
    {
    }

    /**
     * Test attribute "color_field_name"
     */
    public function testPropertyColorFieldName()
    {
    }

    /**
     * Test attribute "qrcode_color_field_name"
     */
    public function testPropertyQrcodeColorFieldName()
    {
    }

    /**
     * Test attribute "number_condition_range_min"
     */
    public function testPropertyNumberConditionRangeMin()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }

    /**
     * Test attribute "check_color_field_required"
     */
    public function testPropertyCheckColorFieldRequired()
    {
    }

    /**
     * Test attribute "combined_field_format"
     */
    public function testPropertyCombinedFieldFormat()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "shape_border_color_field_required"
     */
    public function testPropertyShapeBorderColorFieldRequired()
    {
    }

    /**
     * Test attribute "combined_field_names"
     */
    public function testPropertyCombinedFieldNames()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "number_condition_range_exclusive_min"
     */
    public function testPropertyNumberConditionRangeExclusiveMin()
    {
    }

    /**
     * Test attribute "combined_field_separator"
     */
    public function testPropertyCombinedFieldSeparator()
    {
    }

    /**
     * Test attribute "exclusive_maximum"
     */
    public function testPropertyExclusiveMaximum()
    {
    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {
    }

    /**
     * Test attribute "combined_field_type"
     */
    public function testPropertyCombinedFieldType()
    {
    }

    /**
     * Test attribute "date_time_format"
     */
    public function testPropertyDateTimeFormat()
    {
    }

    /**
     * Test attribute "qrcode_color_field_required"
     */
    public function testPropertyQrcodeColorFieldRequired()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "false_text"
     */
    public function testPropertyFalseText()
    {
    }

    /**
     * Test attribute "strikethrough"
     */
    public function testPropertyStrikethrough()
    {
    }

    /**
     * Test attribute "character_spacing"
     */
    public function testPropertyCharacterSpacing()
    {
    }

    /**
     * Test attribute "number_condition_range_max"
     */
    public function testPropertyNumberConditionRangeMax()
    {
    }

    /**
     * Test attribute "background_color"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "check_color_field_name"
     */
    public function testPropertyCheckColorFieldName()
    {
    }

    /**
     * Test attribute "check_character"
     */
    public function testPropertyCheckCharacter()
    {
    }

    /**
     * Test attribute "rotation"
     */
    public function testPropertyRotation()
    {
    }

    /**
     * Test attribute "option_list"
     */
    public function testPropertyOptionList()
    {
    }

    /**
     * Test attribute "shape_fill_color"
     */
    public function testPropertyShapeFillColor()
    {
    }

    /**
     * Test attribute "string_condition_type"
     */
    public function testPropertyStringConditionType()
    {
    }

    /**
     * Test attribute "shape_fill_color_field_required"
     */
    public function testPropertyShapeFillColorFieldRequired()
    {
    }

    /**
     * Test attribute "decimal_places"
     */
    public function testPropertyDecimalPlaces()
    {
    }

    /**
     * Test attribute "include_time"
     */
    public function testPropertyIncludeTime()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
    }

    /**
     * Test attribute "maximum"
     */
    public function testPropertyMaximum()
    {
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
    }

    /**
     * Test attribute "signature_allow_draw"
     */
    public function testPropertySignatureAllowDraw()
    {
    }

    /**
     * Test attribute "number_condition_type"
     */
    public function testPropertyNumberConditionType()
    {
    }

    /**
     * Test attribute "opacity"
     */
    public function testPropertyOpacity()
    {
    }

    /**
     * Test attribute "minimum"
     */
    public function testPropertyMinimum()
    {
    }

    /**
     * Test attribute "signature_allow_type"
     */
    public function testPropertySignatureAllowType()
    {
    }
}
